_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.11.4
        t:
            "1":
                - 2
                - 3
                - 5
                - 49
                - 51
                - 53
                - 55
                - 105
            "2":
                - 2
                - 3
                - 5
                - 49
                - 51
                - 53
                - 55
                - 105
            "3":
                - 2
                - 3
                - 8
                - 16
                - 23
                - 55
                - 62
            "4": 3.11.4
            "5": 0.18.5
            "8":
                - 1
                - 3
                - 5
            "10":
                - 9
                - 17
            "12": 0.18.5
            "13": windows-amd64
batch_size:
    value: 32
epochs:
    value: 10
image_size:
    value:
        - 224
        - 224
learning_rate:
    value: 0.001
model:
    value: DenseNet121
